_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 5f59fa71-c341-4ea9-8bed-e55b6c04e201
name: Innoraft employee management portal
mail: swarnav.das@innoraft.com
slogan: ''
page:
  403: /node/1
  404: /node/2
  front: /node/4
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
